apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: barkha-app-1
  namespace: default
spec:
  interval: 1m
  path: "./fluxcd/repositories/barkha-app-1/Deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: barkha-app-1
